# Generated by Django 5.1.7 on 2025-05-10 18:05

from django.db import migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('membership', models.PositiveIntegerField()),
                ('post', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
             options={
                'db_table': 'people',
            },
        ),
    ]