# Generated by Django 5.1.7 on 2025-05-10 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_candidate_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='candidate',
            table=None,
        ),
    ]
