# Generated by Django 5.1.7 on 2025-05-01 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_voter_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Voter',
        ),
    ]
