# Generated by Django 5.1.7 on 2025-05-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_candidate_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('membership', models.CharField(max_length=255)),
                ('post', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'people',
            },
        ),
    ]
