# Generated by Django 5.1.7 on 2025-05-02 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='user ID'),
        ),
    ]
