# Generated by Django 5.1.7 on 2025-05-10 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_people'),
    ]

    operations = [
        migrations.DeleteModel(
            name='People',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('users', 'General User')], default='users', max_length=10, verbose_name='User Type'),
        ),
    ]
