# Generated by Django 5.1.7 on 2025-05-11 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_people_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='membership',
            field=models.CharField(max_length=255),
        ),
    ]
