# Generated by Django 5.1.7 on 2025-05-02 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_username_user_user_id_delete_voter'),
        ('accounts', '0006_remove_user_username_alter_user_dob'),
    ]

    operations = [
    ]
