# Generated by Django 5.1.7 on 2025-05-11 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_people'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='people',
            table='candidates.people',
        ),
    ]
