# Generated by Django 5.1.7 on 2025-05-11 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_people_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='people',
            table='people',
        ),
    ]
