# Generated by Django 5.1.7 on 2025-05-11 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_people_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='people',
            table='candidates.people',
        ),
    ]
