# Generated by Django 5.1.7 on 2025-05-11 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_vote_delete_candidate_alter_people_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='people',
            table='people',
        ),
    ]
