# Generated by Django 5.1.7 on 2025-05-11 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_people_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='Vote',
            table='voters',
        ),
    ]
