# Generated by Django 5.1.7 on 2025-05-11 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_vote_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='user',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('name', 'position')},
        ),
    ]
