# Generated by Django 5.1.7 on 2025-05-11 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_rename_user_vote_name_alter_vote_unique_together'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vote',
            new_name='Voter',
        ),
    ]
