# Generated by Django 5.1.7 on 2025-05-11 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_rename_vote_voter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Voter',
            new_name='Vote',
        ),
    ]
